/* Copies the shared Optix theme into this product. Source of truth: ../optix-suite-sdk/theme (do not edit the copies).
   Usage: node scripts/sync-theme.mjs [path-to-theme-folder]
   Writes:
     site/assets/css/optix-theme.css   full shared stylesheet for the marketing website
     site/assets/js/consent.js         AdSense consent loader (public website only)
     assets/css/optix-tokens.css       design tokens only (light + dark) for the web app
     cloud/superadmin/assets/css/optix-tokens.css   the same tokens for the superadmin console
   Dark rules are removed on copy (the suite is light only).
   The app and the console map these tokens onto their own CSS variables in optix-skin.css. */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
/* default: the SDK checkout next to this repo (../optix-suite-sdk), or in ~/Documents; override with an argument or OPTIX_THEME_DIR */
const guesses = [process.argv[2], process.env.OPTIX_THEME_DIR, path.join(root, '..', 'optix-suite-sdk', 'theme'), path.join(root, '..', 'Documents', 'optix-suite-sdk', 'theme')].filter(Boolean).map((p) => path.resolve(p));
const src = guesses.find((d) => fs.existsSync(path.join(d, 'optix-theme.css')));
if (!src) { console.error('optix-suite-sdk/theme not found. Tried:\n  ' + guesses.join('\n  ')); process.exit(1); }
const read = (f) => fs.readFileSync(path.join(src, f), 'utf8');
const put = (rel, text) => { const to = path.join(root, rel); fs.mkdirSync(path.dirname(to), { recursive: true }); fs.writeFileSync(to, text); console.log('wrote', rel); };
const BANNER = '/* Generated by scripts/sync-theme.mjs from optix-suite-sdk/theme — do not edit by hand; change the SDK theme and sync. */\n';

/* The Optix suite is LIGHT ONLY: drop every dark rule (data-theme=dark) so no dark styles ship, whatever the SDK file contains. */
function stripDark(text) {
  let out = '', i = 0;
  while (i < text.length) {
    const open = text.indexOf('{', i);
    if (open < 0) { out += text.slice(i); break; }
    let depth = 1, j = open + 1;
    while (j < text.length && depth) { if (text[j] === '{') depth++; else if (text[j] === '}') depth--; j++; }
    const head = text.slice(i, open);
    if (!/data-theme\s*=\s*["']?dark/.test(head)) out += text.slice(i, j);
    i = j;
  }
  return out;
}
const css = stripDark(read('optix-theme.css'));
/* the tokens are everything before the first global reset rule (`*{box-sizing...}`) */
const cut = css.indexOf('\n*{box-sizing');
if (cut < 0) throw new Error('optix-theme.css changed shape: cannot find the end of the token blocks');
const tokens = css.slice(css.indexOf(':root{'), cut).trim() + '\n';

put('site/assets/css/optix-theme.css', BANNER + css);
put('site/assets/js/consent.js', BANNER.replace('/*', '//').replace(' */', '') + read('consent.js'));
put('assets/css/optix-tokens.css', BANNER + tokens);
put('cloud/superadmin/assets/css/optix-tokens.css', BANNER + tokens);
